url: git.erock.io
repos:
  - path: /home/erock/dev/pico/pico
    refs:
      - main
      - v1.0.0
    desc: pico services - prose.sh, lists.sh, pastes.sh, imgs.sh, feeds.sh, pgs.sh
  - path: /home/erock/dev/pico/pico-ops
    refs:
      - main
    desc: infra for pico services
  - path: /home/erock/dev/app-ui
    refs:
      - main
    desc: aptible's paas web application
