name: static
on:
  push:
    branches:
      - main
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # need entire history
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: install pgit
        run: |
          go get github.com/picosh/pgit
          go install github.com/picosh/pgit
      - name: generate site
        run: |
          pgit --out ./public --label pgit --desc "static site generator for git" --clone-url "https://github.com/picosh/pgit.git" --revs main
          pgit --out ./public --assets
      - name: upload to pgs
        run: |
          echo -e "${{ secrets.PRIVATE_KEY }}" >__TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          scp -s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -r ./public/* erock@pgs.sh:/git
