name: static
on:
  push:
    branches:
      - main
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # need entire history
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: install pgit
        run: |
          go get github.com/picosh/pgit
          go install github.com/picosh/pgit
      - name: generate site
        run: |
          pgit --out ./public --label pgit --desc "static site generator for git" --clone-url "https://github.com/picosh/pgit.git" --revs main
          pgit --out ./public --assets
      - name: publish to pgs
        uses: picosh/pgs-action@main
        with:
          user: erock
          key: ${{ secrets.PRIVATE_KEY }}
          src: './public/*'
          project: 'git'
