name: static
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go install github.com/picosh/pgit
      - run: pgit --out ./public --label pgit
      - run: pgit --out ./public --assets
